---
sudo: required
language: python
python: "2.7"

env:
  - PLAYBOOK=tests/playbook-travis.yml INVENTORY=tests/inventory

before_install:
  - sudo apt-get remove ruby rubygems ruby-dev libruby1.8 ruby1.8 ruby1.8-dev rubygems1.8
  - dpkg --get-selections |grep ruby
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl

install:
  # Install Ansible.
  - sudo pip install ansible

before_script:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - echo localhost > $INVENTORY

script:
  # Check playbook's syntax.
  - "ansible-playbook $PLAYBOOK -i $INVENTORY --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook $PLAYBOOK -i $INVENTORY --connection=local --sudo"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook $PLAYBOOK -i $INVENTORY --connection=local --sudo"

#  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook $PLAYBOOK -i $INVENTORY --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

  # Tests to make sure Mailcatcher is running and responds.
  - (sleep 5; curl http://localhost:1080) || exit 1
