---
- include_vars: "{{ ansible_os_family }}.yml"

- name: RedHat | Install mailcatcher dependencies
  yum: pkg={{ item }} state=present
  with_items:
      - gcc
      - gcc-c++
      - sqlite-devel
      - ruby-devel
      - redhat-lsb
      - rubygems
  when: ansible_os_family == 'RedHat'

- name: Debian | Install mailcatcher dependencies
  apt: pkg={{ item }} state=present
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby1.9.3
      - rubygems1.9.1
      - ruby1.9.1-dev
  when: ansible_os_family == 'Debian'
  register: mailcatcher_dependencies_install
  changed_when: mailcatcher_dependencies_install.stdout.find('No packages will be installed, upgraded, or removed') == false

- name: Check if mailcatcher not already installed
  stat:
    path=/usr/local/bin/mailcatcher
  register: mailcatcher_installed

- name: Install Mailcatcher
  command: gem install mailcatcher
  when: not mailcatcher_installed.stat.exists

- name: Create upstart script for mailcatcher
  template: src=upstart.j2 dest=/etc/init/mailcatcher.conf mode=0644
  notify:
    - restart mailcatcher
  when: ansible_os_family == 'RedHat' and ansible_distribution_version < 7

- name: Create sysvinit script for mailcatcher
  template: src=sysvinit.j2 dest=/etc/init.d/mailcatcher mode=0755
  notify:
    - restart mailcatcher
  when: (ansible_distribution == 'Debian' and ansible_lsb.major_release|int < 8) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= '14')


- name: Create systemd script for mailcatcher
  template: src=systemd.j2 dest="{{ systemd_dir }}/mailcatcher.service" mode=0644
  notify:
    - restart mailcatcher
  when: (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= '15') or
        (ansible_os_family == 'RedHat' and ansible_distribution_version >= 7)

- name: Enable mailcatcher service
  service: name=mailcatcher state=started enabled=yes
  when: ((ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8) or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= '15') or
        (ansible_os_family == 'RedHat' and ansible_distribution_version >= 7)) and
        mailcatcher_autostart|bool
